### ISSUE TITLE
Exception - when have_received failure message is constructed with nil arguments

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [pivotal/cedar#306]
This line works fine when it passes:

object should have_received(@selector(selectorWithArg1:arg2:)).with(arg1).and_with(nil);

But when it fails and cedar attempts to construct the failure message it crashes at:
line 86 of NSInvocation_Cedar.m called by
line 132 of HaveReceived.h

Suggestion: return an NSPointerArray from arguments instead of an NSArray

**Comment by akitchen** [comment]
hi @xtreme-gavin-enns - thanks for getting in touch.

I think I reproduced this, or something like it.

Under conditions where this is a passing test case:
```
object should have_received(@selector(selectorWithArg1:arg2:)).with(arg1).and_with(nil);
```
This expectation failure blows up inappropriately:
```
object should have_received(@selector(selectorWithArg1:arg2:)).with(arg1).and_with(@666);
```
I'll open a pr shortly

**Comment by akitchen** [comment]
Here's the story in tracker: https://www.pivotaltracker.com/story/show/86329706

**Comment by akitchen** [comment]
This has been fixed.  Thanks again.
