### ISSUE TITLE
Cedar templates adding extra "Spec" to the name of the class (Xcode 6.3)

### ISSUE THREAD

**Issue by pivotal-ryan-mcleod** [pivotal/cedar#324]
Not sure if this is specific to Xcode 6.3 or even to my specific machine, but for whatever reason when I add a Cedar spec file to the project, it adds "Spec" to the end of the class name and not just the name of the spec class, which results in the SPEC_BEGIN() being suffixed with "SpecSpec". As below:

```
#import <Cedar/Cedar.h>
#import "ClassNameSpec.h"

using namespace Cedar::Matchers;
using namespace Cedar::Doubles;

SPEC_BEGIN(ClassNameSpecSpec)

describe(@"ClassNameSpec", ^{
    __block ClassNameSpec *<#object under test#>;

    beforeEach(^{

    });
});

SPEC_END
```

The template looks fine, so I'm not really sure what's going on:
```
#import <Cedar/Cedar.h>
#import "___FILEBASENAME___.h"

using namespace Cedar::Matchers;
using namespace Cedar::Doubles;

SPEC_BEGIN(___FILEBASENAMEASIDENTIFIER___Spec)

describe(@"___FILEBASENAMEASIDENTIFIER___", ^{
    __block ___FILEBASENAMEASIDENTIFIER___ *<#object under test#>;

    beforeEach(^{

    });
});

SPEC_END
```

The filename is also correct. I.e., it is ClassNameSpec.mm, not ClassNameSpecSpec.mm

**Comment by joemasilotti** [comment]
FWIW I'm seeing the same thing running Xcode 6.3 on multiple machines.

**Comment by pivotal-ryan-mcleod** [comment]
It kinda seems like the `___FILEBASENAMEASIDENTIFIER___` and `__FILEBASENAME__` are now returning the full file name (minus the extension) instead of what was entered into the field. When I change the template to create `__FILEBASENAME__.mm` instead of  `__FILEBASENAME__Spec.mm` it works fine, except that the file is misnamed. Possible bug in Xcode?

**Comment by tjarratt** [comment]
I've been noticing this too with lately. Interestingly enough, Xcode actually changes __FILEBASENAME__ (and related) between the time the filename is created, and the time the template is filled out. I was able to verify this by changing the template from `__FILEBASENAME__SPEC.mm` to `__FILEBASENAME__FOO.mm`.

I suppose a workaround right now would be to have two copies of the Spec templates, and check the xcode version before we install so we can include the correct one.

**Comment by akitchen** [comment]
But then what happens if the user has multiple Xcodes installed? And what happens if they upgrade?




😿
