### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by younata** [pivotal/cedar#328]
Yo.

Cedar doesn't even build when using Carthage.

Cartfile:

```
github "pivotal/cedar"
```

output when running:

```bash
$ carthage update --platform iOS
*** Cloning cedar
*** Checking out cedar at "v0.11.3"
Parse error: expected submodule commit SHA in ls-tree output:
Segmentation fault: 11
```

Might be something worth looking into.

Also, there needs to be a shared schema that produces a .framework in order for carthage support to actually be a thing. I'm not certain if that's actually supported at the moment.

**Comment by akitchen** [comment]
I was hoping this was a pull request when I saw the email 😔

There was a separate effort to support iOS frameworks which has stalled. There are some related stories in the tracker project and possibly a branch to look at. @jeffh might have some context. Sorry I don't have links handy at the moment.

**Comment by younata** [comment]
I'll probably end up doing this either later today or over the weekend. I'm going to take care of blindside, ksdeferred and robot first, then look at this.

**Comment by younata** [comment]
I'll close this in deference to the pull request I made earlier.
