### ISSUE TITLE
Exceptions on failures

### ISSUE THREAD

**Issue by pivotal-domenic-curro** [pivotal/cedar#331]
I find that I now turn off 'All Exceptions' breakpoints during my development cycle, because of testing.  I find All Exceptions breakpoints to be extremely helpful outside of testing.  When tests actually except, I would like to know about it, but when a test merely fails, I don't need the exception.

Is there a way to disable throwing exceptions for failing tests?

**Comment by akitchen** [comment]
From my standpoint, I've long been in the habit of simply toggling breakpoints and continuing from the keyboard, depending on what I'm trying to do.  The use of an exception breakpoint to jump immediately into a failing test with context can be very helpful.

**Comment by akitchen** [comment]
The backstory here has to do with our heavy use of OCMock in the old days, and wanting exceptions to trigger spec failures.  That said, this mechanism is central to the way the cedar runner currently works.  I think we may revisit this as we consider how best to support other matcher libs (e.g. Nimble) but for now I don't anticipate any changes.

PRs and/or refactoring suggestions are super welcome, but I'm going to close this for now.  Thanks for bringing it up.
