### ISSUE TITLE
'memory' file not found when building Cedar

### ISSUE THREAD

**Issue by ratkins** [pivotal/cedar#341]
I'm trying to get a cedar-using project up and running under Xcode 7. We've changed the Podfile to specify `:branch => 'Xcode7'` (btw, which of branch `Xcode7` and `xcode7` is correct?) which fixed some things, but now Xcode is choking on the `#import <memory>` line of `Argument.h`, saying `'memory' file not found`.

So for some reason it can't find the C++ standard libraries? This is a cocoapods project and the error is emanating from the `FooTests` build product (is that what you call it?), so it may be a cocoapods-related thing, or maybe something needs to be fixed in the Cedar Podspec, or...

I've fiddled with the "C++ language dialect" and "C++ standard library" settings of the test target (putting them to "Compiler Default") but it doesn't seem to make any difference.

Any hints?

**Comment by akitchen** [comment]
Cocoa pods should already be adding the correct settings to the project, as it has for some time. But changes to support iOS dynamic framework require all public headers to be imported in the framework umbrella header.




This means that any file that imports Cedar will need to be ObjC++. Try changing the suffix of the file importing cedar to .mm and see if the problem goes away.

**Comment by ratkins** [comment]
The top-level Cedar import is in the `FooTests-Prefix.pch`, and everything else is a `.mm`.

**Comment by tjarratt** [comment]
Hey @ratkins, thanks for filing this issue. I thought that I had pushed my changes to the `Xcode7` branch (uppercase X), but apparently I had pushed it to the `xcode7` branch instead. 

Can you give it a whirl again with the `Xcode7` branch, that should be the correct one. I just pushed the one commit that fixed XCTest bundles about a minute ago.

**Comment by ratkins** [comment]
:thumbsup:

It all compiles and the tests run now! Thanks!

**Comment by akitchen** [comment]
Could we kill the branch that shouldn't be used?  I didn't realize we had this collision.

BTW these changes were introduced in order to support Carthage.  Not sure if that is a preferable workflow for you @ratkins , but it might be worth giving it a shot.

**Comment by ratkins** [comment]
Hmm. I've checked out a clean copy of the original project, made the other changes and now it doesn't work under Xcode 7 anymore. Will investigate further tomorrow.

**Comment by ratkins** [comment]
... aand, now I'm getting the same error under Xcode 6.3.2.

**Comment by tjarratt** [comment]
That's correct, building cedar from any commit after e4a6b833688a6504f237f50249c8626adc867338,  (regardless of the xcode version) demands that the files importing `Cedar.h` be C++, (including anything might use a .pch that imports Cedar.h as well).

I'll update the title for the issue to better reflect that.

**Comment by ratkins** [comment]
Do we know what the fix is?

**Comment by tjarratt** [comment]
The fix is for all source files that import Cedar.h to be .mm (objc++)

(Sent from a tiny keyboard. Typos are not intentional)

On Thursday, June 25, 2015, Robert Atkins <notifications@github.com> wrote:

> Do we know what the fix is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pivotal/cedar/issues/341#issuecomment-115305020>.
>


-- 
Magnetized From My Etch-A-Sketch

**Comment by ratkins** [comment]
Aha, I've got it now—there were some (unnecessary, as it turned out) .m files fouling the pool that I'd deleted at one point and then came back again after I'd started from scratch.
