### ISSUE TITLE
Properties of nice fakes are not key value coding-compliant

### ISSUE THREAD

**Issue by pivotal-tom-mcneely** [pivotal/cedar#355]
I am using key value observation to observe a property on a class that I would like to fake for testing.

I get the following exception thrown by Cedar:

```<CDRClassFake 0x7f8e1b63add0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key propertyName.```

**Comment by akitchen** [comment]
hi @pivotal-tom-mcneely !

Could you provide a bit more context?  This is a somewhat complicated issue.

**Comment by briancroom** [comment]
As I understand it, this has been sufficiently addressed by #357. Thanks @pivotal-tom-mcneely for raising this issue and please let us know if you have more concerns!
