### ISSUE TITLE
Test observation issues

### ISSUE THREAD

**Issue by idoru** [pivotal/cedar#383]
Starting with Xcode 7.3 test output from test bundles is no longer produced. Similar to this issue with Nimble:

https://github.com/Quick/Nimble/issues/270

Furthermore, attempts to fix it (#382) introduced problems with xctest. Similar to this issue with Nimble:

https://github.com/Quick/Nimble/issues/273

**Comment by phatblat** [comment]
Please dup [rdar://25456276](https://openradar.appspot.com/25456276) so Apple is aware we are running into these issues.

**Comment by briancroom** [comment]
Resolved by #384.
