### ISSUE TITLE
Installing template fails on AppCode 2016.1

### ISSUE THREAD

**Issue by mbajic** [pivotal/cedar#392]
Trying to install cedar shortcuts and templates fails with the latest AppCode (2016.1). There's no output as to why. After running rake install manually it narrows it down to

```
[Failed] Command: cp "/Users/pivotal/workspace/cedar/CodeSnippetsAndTemplates/AppCodeSnippets/Cedar.xml" "/Users/pivotal/Library/Preferences/AppCode2016.1/templates/Cedar.xml"
```

Just creating the templates directory manually resolves the issue.

**Comment by tjarratt** [comment]
Thanks for reporting this @mbajic -- sorry it took so many months to resolve it.

Should be fixed at the edge of master -- I'm hopeful to cut a release of Cedar soon, for the Xcode 8 GM.
